# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/analytics.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 848)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.clients_action = QtWidgets.QAction(MainWindow)
        self.clients_action.setObjectName("clients_action")
        self.suppliers_action = QtWidgets.QAction(MainWindow)
        self.suppliers_action.setObjectName("suppliers_action")
        self.products_action = QtWidgets.QAction(MainWindow)
        self.products_action.setObjectName("products_action")
        self.warehouse_action = QtWidgets.QAction(MainWindow)
        self.warehouse_action.setObjectName("warehouse_action")
        self.orders_action = QtWidgets.QAction(MainWindow)
        self.orders_action.setObjectName("orders_action")
        self.deliveries_action = QtWidgets.QAction(MainWindow)
        self.deliveries_action.setObjectName("deliveries_action")
        self.users_action = QtWidgets.QAction(MainWindow)
        self.users_action.setObjectName("users_action")
        self.analytics_action = QtWidgets.QAction(MainWindow)
        self.analytics_action.setObjectName("analytics_action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Аналитика"))
        self.clients_action.setText(_translate("MainWindow", "Клиенты"))
        self.suppliers_action.setText(_translate("MainWindow", "Поставщики"))
        self.products_action.setText(_translate("MainWindow", "Продукты"))
        self.warehouse_action.setText(_translate("MainWindow", "Склад"))
        self.orders_action.setText(_translate("MainWindow", "Заказы"))
        self.deliveries_action.setText(_translate("MainWindow", "Поставки"))
        self.users_action.setText(_translate("MainWindow", "Пользователи"))
        self.analytics_action.setText(_translate("MainWindow", "Аналитика"))
