# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/createupdatewarehouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateUpdateWarehouseWindow(object):
    def setupUi(self, CreateUpdateWarehouseWindow):
        CreateUpdateWarehouseWindow.setObjectName("CreateUpdateWarehouseWindow")
        CreateUpdateWarehouseWindow.resize(491, 252)
        self.centralwidget = QtWidgets.QWidget(CreateUpdateWarehouseWindow)
        self.centralwidget.setObjectName("centralwidget")
        CreateUpdateWarehouseWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateUpdateWarehouseWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 21))
        self.menubar.setObjectName("menubar")
        CreateUpdateWarehouseWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateUpdateWarehouseWindow)
        self.statusbar.setObjectName("statusbar")
        CreateUpdateWarehouseWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CreateUpdateWarehouseWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateUpdateWarehouseWindow)

    def retranslateUi(self, CreateUpdateWarehouseWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateUpdateWarehouseWindow.setWindowTitle(_translate("CreateUpdateWarehouseWindow", "Добавить / изменить товар на складе"))
