# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/createupdateclient.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateUpdateClient(object):
    def setupUi(self, CreateUpdateClient):
        CreateUpdateClient.setObjectName("CreateUpdateClient")
        CreateUpdateClient.resize(662, 265)
        self.centralwidget = QtWidgets.QWidget(CreateUpdateClient)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        CreateUpdateClient.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateUpdateClient)
        QtCore.QMetaObject.connectSlotsByName(CreateUpdateClient)

    def retranslateUi(self, CreateUpdateClient):
        _translate = QtCore.QCoreApplication.translate
        CreateUpdateClient.setWindowTitle(_translate("CreateUpdateClient", "Создать клиента"))
        self.label.setText(_translate("CreateUpdateClient", "Компания"))
        self.label_2.setText(_translate("CreateUpdateClient", "Адрес"))
        self.label_3.setText(_translate("CreateUpdateClient", "Телефон"))
        self.label_4.setText(_translate("CreateUpdateClient", "Email"))
        self.pushButton.setText(_translate("CreateUpdateClient", "Создать клиента"))
