# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/orders.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 437)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.clients_action = QtWidgets.QAction(MainWindow)
        self.clients_action.setObjectName("clients_action")
        self.suppliers_action = QtWidgets.QAction(MainWindow)
        self.suppliers_action.setObjectName("suppliers_action")
        self.products_action = QtWidgets.QAction(MainWindow)
        self.products_action.setObjectName("products_action")
        self.warehouse_action = QtWidgets.QAction(MainWindow)
        self.warehouse_action.setObjectName("warehouse_action")
        self.orders_action = QtWidgets.QAction(MainWindow)
        self.orders_action.setObjectName("orders_action")
        self.deliveries_action = QtWidgets.QAction(MainWindow)
        self.deliveries_action.setObjectName("deliveries_action")
        self.users_action = QtWidgets.QAction(MainWindow)
        self.users_action.setObjectName("users_action")
        self.analytics_action = QtWidgets.QAction(MainWindow)
        self.analytics_action.setObjectName("analytics_action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Заказы"))
        self.pushButton.setText(_translate("MainWindow", "Найти заказ"))
        self.pushButton_5.setText(_translate("MainWindow", "Статусы заказов"))
        self.pushButton_4.setText(_translate("MainWindow", "Изменить заказ"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить заказ"))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить заказ"))
        self.clients_action.setText(_translate("MainWindow", "Клиенты"))
        self.suppliers_action.setText(_translate("MainWindow", "Поставщики"))
        self.products_action.setText(_translate("MainWindow", "Продукты"))
        self.warehouse_action.setText(_translate("MainWindow", "Склад"))
        self.orders_action.setText(_translate("MainWindow", "Заказы"))
        self.deliveries_action.setText(_translate("MainWindow", "Поставки"))
        self.users_action.setText(_translate("MainWindow", "Пользователи"))
        self.analytics_action.setText(_translate("MainWindow", "Аналитика"))
