# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/updateproduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateUpdateProductWIndow(object):
    def setupUi(self, CreateUpdateProductWIndow):
        CreateUpdateProductWIndow.setObjectName("CreateUpdateProductWIndow")
        CreateUpdateProductWIndow.resize(462, 286)
        self.centralwidget = QtWidgets.QWidget(CreateUpdateProductWIndow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        CreateUpdateProductWIndow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateUpdateProductWIndow)
        QtCore.QMetaObject.connectSlotsByName(CreateUpdateProductWIndow)

    def retranslateUi(self, CreateUpdateProductWIndow):
        _translate = QtCore.QCoreApplication.translate
        CreateUpdateProductWIndow.setWindowTitle(_translate("CreateUpdateProductWIndow", "Изменить/Добавить продукты"))
        self.label.setText(_translate("CreateUpdateProductWIndow", "Название"))
        self.label_2.setText(_translate("CreateUpdateProductWIndow", "Категория"))
        self.label_3.setText(_translate("CreateUpdateProductWIndow", "Цена закупки"))
        self.label_6.setText(_translate("CreateUpdateProductWIndow", "Наценка, %"))
        self.label_5.setText(_translate("CreateUpdateProductWIndow", "Ед-изм"))
        self.pushButton.setText(_translate("CreateUpdateProductWIndow", "Сохранить"))
