# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/warehouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarehouseWindow(object):
    def setupUi(self, WarehouseWindow):
        WarehouseWindow.setObjectName("WarehouseWindow")
        WarehouseWindow.resize(547, 251)
        self.centralwidget = QtWidgets.QWidget(WarehouseWindow)
        self.centralwidget.setObjectName("centralwidget")
        WarehouseWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WarehouseWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 21))
        self.menubar.setObjectName("menubar")
        WarehouseWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WarehouseWindow)
        self.statusbar.setObjectName("statusbar")
        WarehouseWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WarehouseWindow)
        QtCore.QMetaObject.connectSlotsByName(WarehouseWindow)

    def retranslateUi(self, WarehouseWindow):
        _translate = QtCore.QCoreApplication.translate
        WarehouseWindow.setWindowTitle(_translate("WarehouseWindow", "Склад"))
